In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataMain = pd.read_csv('data.csv')

In [2]:
dataMain.head(10)
data=dataMain.head(10)
print(data)


  Weather Temperature Humidity  Wind Golf Play
0    fine         hot     high  none        no
1    fine         hot     high   few        no
2   cloud         hot     high  none       yes
3    rain        warm     high  none       yes
4    rain        cold   medium  none       yes
5    rain        cold   medium   few        no
6   cloud        cold   medium   few       yes
7    fine        warm     high  none        no
8    fine        cold   medium  none       yes
9    rain        warm   medium  none       yes


In [15]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
wE=le.fit_transform(data['Weather'])
print (wE)
tE=le.fit_transform(data['Temperature'])
print (tE)
hE=le.fit_transform(data['Humidity'])
print (hE)
wnE=le.fit_transform(data['Wind'])
print (wnE)
gE=le.fit_transform(data['Golf Play'])
print (gE)
data0=zip(wE,tE,hE,wnE,gE)
print(data0)

[1 1 0 2 2 2 0 1 1 2]
[1 1 1 2 0 0 0 2 0 2]
[0 0 0 0 1 1 1 0 1 1]
[1 0 1 1 1 0 0 1 1 1]
[0 0 1 1 1 0 1 0 1 1]


In [17]:
from sklearn.model_selection import train_test_split
var=data.values[:,0:4]
tar=data.values[:,4]
#     tar=tar.reshape(-1, 1)
#Splitting the data
var_train, var_test, tar_train, tar_test = train_test_split(var,tar, test_size = 0.3, random_state = 100) 

In [19]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics


model=GaussianNB()
    
#Training the model
model.fit(var_train, tar_train)
#Predicting the response
tar_pred=model.predict(var_test)
print("Accuracy:",metrics.accuracy_score(tar_test, tar_pred))

ValueError: could not convert string to float: 'rain'